spring:
  flyway:
    schemas: kraechz
    create-schemas: true
    url: jdbc:mariadb://localhost:3307/
    user: root
    password: kraechz
  datasource:
    url: jdbc:mariadb://localhost:3307/kraechz
    username: root
    password: kraechz